/**
 * Express app factory.
 *
 * Exported separately from `index.ts` so tests can build an app without binding
 * a port (`const app = createApp()` then use supertest or call routes directly).
 */
import express, { type Express } from 'express';
import cors from 'cors';
import { env } from './config/env';
import { logger } from './core/logger';
import { requestContext } from './api/middleware/request-context';
import { errorHandler, notFoundHandler } from './api/middleware/error-handler';
import { API_PREFIX, buildApiRouter } from './api/router';
import { healthRouter } from './api/routes/meta.routes';

export function createApp(): Express {
  const app = express();

  // Behind a proxy in any hosted demo; needed for correct client IPs.
  app.set('trust proxy', true);
  app.disable('x-powered-by');

  /* ------------------------------ middleware ----------------------------- */
  app.use(
    cors({
      origin: env.corsOrigins.length ? env.corsOrigins : true,
      credentials: true,
      exposedHeaders: ['x-request-id'],
    }),
  );
  app.use(express.json({ limit: '1mb' }));
  app.use(express.urlencoded({ extended: true }));
  app.use(requestContext);

  /* --------------------------- request logging --------------------------- */
  app.use((req, res, next) => {
    // SSE connections are long-lived; logging them on finish would be noise.
    if (req.path.endsWith('/stream')) {
      logger.debug(`--> ${req.method} ${req.originalUrl} (SSE)`, { requestId: req.requestId });
      next();
      return;
    }
    res.on('finish', () => {
      const level = res.statusCode >= 500 ? 'error' : res.statusCode >= 400 ? 'warn' : 'info';
      logger[level](`${req.method} ${req.originalUrl} ${res.statusCode}`, {
        requestId: req.requestId,
        durationMs: Date.now() - req.startedAtMs,
      });
    });
    next();
  });

  /* -------------------------------- routes ------------------------------- */
  // Health probes live at the root, outside the versioned API.
  app.use('/', healthRouter);
  app.use(API_PREFIX, buildApiRouter());

  /**
   * Mock asset endpoint. The Logistics Agent generates label URLs like
   * `/mock-assets/labels/LBL-000001.pdf`; this returns a placeholder so the UI
   * can render a working download link without a real label service.
   */
  app.get('/mock-assets/labels/:labelId', (req, res) => {
    res.type('text/plain').send(
      [
        '=== COSMIC MART RETURN LABEL (MOCK) ===',
        `Label: ${req.params.labelId}`,
        'This is a placeholder generated by the demo backend.',
        'No real carrier integration exists — see PRD section 12 (out of scope).',
      ].join('\n'),
    );
  });

  /* ------------------------------ API index ------------------------------ */
  app.get('/', (_req, res) => {
    res.ok({
      name: 'Cosmic Return Navigator API',
      version: '0.1.0',
      status: 'wireframe',
      apiPrefix: API_PREFIX,
      documentation: {
        routes: `${API_PREFIX}/meta/routes`,
        pipeline: `${API_PREFIX}/meta/pipeline`,
        errorCodes: `${API_PREFIX}/meta/error-codes`,
        agents: `${API_PREFIX}/agents`,
        scenarios: `${API_PREFIX}/demo/scenarios`,
      },
    });
  });

  /* ------------------------------ terminals ------------------------------ */
  app.use(notFoundHandler);
  app.use(errorHandler);

  return app;
}
